#!/usr/bin/env python
# encoding: utf-8
# Auther: Yosuke Hirano
import rospy
from std_msgs.msg import Int32

def cb(message):
        rospy.loginfo(message)
def cb2(message):
        rospy.loginfo(message)

if __name__ == '__main__':
    rospy.init_node('primenum_sub')
    sub = rospy.Subscriber( 'primenum_quanti', Int32, cb)
    sub2 = rospy.Subscriber( 'primenum_up', Int32, cb2)
    rospy.spin()

