#!/usr/bin/env python
# encoding: utf-8
# Author: Yosuke Hirano

import time
import rospy
from std_msgs.msg import Int32

if __name__ == '__main__':
    # code
    rospy.init_node('primenum')
    pub = rospy.Publisher('primenum_quanti', Int32, queue_size=1)
    pub2 = rospy.Publisher('primenum_up', Int32, queue_size=1)
    rate = rospy.Rate(5)
    num = 1000
    q = 0
    for i in range(2, num):
        for j in range(2, i+1):
            if i % j == 0:
                if i == j:
		    q += 1
		    pub.publish(q)
	            time.sleep(0.1)
                    pub2.publish(i)
                    rate.sleep()
                else:
                    break

